name: PlatformIO release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: break if not run on master branch
        if: ${{ github.base_ref == 'master' }}
        run: exit -1
      - uses: actions/checkout@v2
      - name: pip caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: PlatformIO caching
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Python setup
        uses: actions/setup-python@v2
      - name: PlatformIO installation
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: PlatformIO run
        run: pio run
      - name: upload artifacts (firmware files)
        uses: actions/upload-artifact@v2
        with:
          name: firmwares
          path: .pio/build/*/firmware.*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts (firmware files)
        uses: actions/download-artifact@v2
        with:
          name: firmwares
          path: ~/artifacts
      - name: ls for artifact directors
        run: ls -ahlR ~/artifacts
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: ~/artifacts/*
          prerelease: true
